"""Decomposition of debt dynamics and counterfactual replays."""

import numpy as np
import pytest

from public_debt import accounting, synthetic


@pytest.fixture(scope="module")
def fiscal():
    return synthetic.fiscal_dataset()


def test_decomposition_closes_the_identity(fiscal):
    dec = accounting.debt_decomposition(fiscal)
    total = dec["primary deficit"] + dec["snowball"] + dec["stock-flow adjustment"]
    np.testing.assert_allclose(total, dec["change in debt"], atol=1e-14)
    np.testing.assert_allclose(dec["snowball"], dec["interest"] + dec["real growth"] + dec["inflation"], atol=1e-15)


def test_stock_flow_adjustment_is_recovered(fiscal):
    # The synthetic data are generated by the identity with known stock-flow adjustments.
    rng = np.random.default_rng(5)
    n = len(fiscal)
    rng.standard_normal(n), rng.standard_normal(n), rng.standard_normal(n)
    expected_sfa = 0.003 * rng.standard_normal(n)
    dec = accounting.debt_decomposition(fiscal)
    np.testing.assert_allclose(dec["stock-flow adjustment"], expected_sfa[1:], atol=1e-12)


def test_counterfactual_without_changes_reproduces_history(fiscal):
    path = accounting.counterfactual(fiscal, 2000)
    np.testing.assert_allclose(path, fiscal.loc[2001:, "debt"], rtol=1e-12)


def test_counterfactual_higher_primary_balance_lowers_debt(fiscal):
    base = accounting.counterfactual(fiscal, 2000)
    better = accounting.counterfactual(fiscal, 2000, primary_balance=fiscal["primary_balance"] + 0.01)
    assert np.all(better < base)
    # One point more of primary balance for one year lowers the next debt ratio by exactly one point.
    assert base.iloc[0] - better.iloc[0] == pytest.approx(0.01, abs=1e-14)


def test_stabilising_primary_balance_formula():
    assert accounting.stabilising_primary_balance(1.0, 0.05, 0.0, 0.0) == pytest.approx(0.05)
    assert accounting.stabilising_primary_balance(1.2, 0.03, 0.01, 0.02) == pytest.approx(1.2 * (0.03 - 0.0302) / 1.0302)


def test_by_period_sums_years(fiscal):
    dec = accounting.debt_decomposition(fiscal)
    table = accounting.by_period(dec, {"a": (1996, 2000), "b": (2001, 2024)})
    np.testing.assert_allclose(table.sum(), dec.sum(), atol=1e-13)
